# Generated by Django 4.2.5 on 2023-10-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('operating_state', models.CharField(max_length=100)),
                ('set_temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('mode', models.CharField(max_length=100)),
                ('reload_interval', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('last_updated', models.DateTimeField(verbose_name='date updated')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_name', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_identifier', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemonitor.sensortype')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created', models.DateTimeField(verbose_name='date recorded')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemonitor.sensor')),
            ],
        ),
    ]
