# Generated by Django 4.2.5 on 2023-10-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='reload_interval',
            field=models.IntegerField(default=5),
        ),
    ]
