# Generated by Django 4.2.5 on 2023-10-04 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0002_alter_device_reload_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='climatemonitor.sensortype'),
        ),
        migrations.CreateModel(
            name='ThermostatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_state', models.CharField(max_length=100)),
                ('set_temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('mode', models.CharField(max_length=100)),
                ('created', models.DateTimeField(verbose_name='date recorded')),
                ('thermostat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='climatemonitor.thermostat')),
            ],
        ),
    ]
