# Generated by Django 4.2.5 on 2023-10-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0003_thermostat_alter_sensor_sensor_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
