# Generated by Django 4.2.6 on 2023-10-09 22:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0004_delete_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='color',
            field=colorfield.fields.ColorField(default='#696969', image_field=None, max_length=25, samples=None),
        ),
    ]
