# Generated by Django 4.2.6 on 2023-10-09 22:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0005_sensor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermostat',
            name='set_color',
            field=colorfield.fields.ColorField(default='#696969', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='state_color',
            field=colorfield.fields.ColorField(default='#FFA500', image_field=None, max_length=25, samples=None),
        ),
    ]
