# Generated by Django 4.2.6 on 2023-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0006_thermostat_set_color_thermostat_state_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermostathistory',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=20.6, max_digits=5),
            preserve_default=False,
        ),
    ]
