# Generated by Django 4.2.6 on 2023-11-16 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climatemonitor', '0008_settings_usersettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
    ]
