# Generated by Django 4.2.6 on 2024-01-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0009_rename_settings_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('threshold_mintue', models.DecimalField(decimal_places=1, max_digits=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('override_temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('deleted', models.BooleanField(default=False)),
                ('override_sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='override_sensors', to='climatemonitor.sensor')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='climatemonitor.sensor')),
            ],
        ),
    ]
