# Generated by Django 4.2.6 on 2024-01-11 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0010_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='date recorded')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='climatemonitor.alarm')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('deleted', models.BooleanField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='climatemonitor.alarm')),
            ],
        ),
    ]
