# Generated by Django 4.2.6 on 2024-01-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0011_alarmhistory_alarmemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='threshold_mintue',
            field=models.DurationField(),
        ),
    ]
