# Generated by Django 4.2.6 on 2024-01-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemonitor', '0012_alter_alarm_threshold_mintue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='threshold_mintue',
            new_name='threshold',
        ),
    ]
